spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://localhost/mysql
    password: ps123456
    driver-class-name: com.mysql.jdbc.Driver
    username: root

server:
    port: 8880

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
