eureka:
  instance:
    preferIpAddress: true 
    hostname: localhost
  client:
    registerWithEureka: true 
    fetchRegistry: false 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  
spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://localhost/mydb
    password: ps123456
    driver-class-name: com.mysql.jdbc.Driver
    username: root
server:
  port: 8880
